# Site settings
title: Codetrepreneur
email: 
description: > # this means to ignore newlines until "baseurl:"
  Helping you build your dreams.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codetrepreneur.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
